### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by cgaebel** [napcs/programming_for_kids#1]
The book needs a "getting started" for python and ruby. Sure, kids can type the code listing, but as it stands no 4th grader has any hope of running it. A simplified one than what is supplied by the websites is best, as they are young children.

**Comment by napcs** [comment]
Good idea. Feel free to write one :)  
I can certainly take a stab at the Ruby side :)

**Comment by cgaebel** [comment]
I'll see what I can do for python.

**Comment by napcs** [comment]
I've put the Ruby install instructions up.

**Comment by cgaebel** [comment]
This can be closed.
